"""Add reset_token and reset_token_expiration to User model

Revision ID: c85d9599b2f0
Revises: be1109536604
Create Date: 2025-09-17 09:36:48.273254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85d9599b2f0'
down_revision: Union[str, Sequence[str], None] = 'be1109536604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['reset_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'reset_token_expiration')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
